databases:
  - name: fintoc_ecomerce-db
    databaseName: fintoc_ecomerce_db
    user: fintoc_ecomerce
    plan: free

services:
  - type: web
    name: fintoc_ecomerce-app
    env: python
    buildCommand: "./render-build.sh"
    startCommand: "gunicorn run:fintoc_ecomerce_app"
    plan: free
    envVars:
        - key: DATABASE_URL
          fromDatabase:
            name: fintoc_ecomerce-db
            property: connectionString